### ISSUE TITLE
Blocks missing loot table

### ISSUE THREAD

**Issue by WenXin20** [manmaed/CutePuppyMod#3]
### CutePuppyMod version

0.7.4

### Minecraft Version

1.16.5

### Forge Version

36.1.32

### Do you have optifine installed?

I have other rendering based mods installed

### Describe the issue

Core blocks are missing loot tables, which means it does not drop the block when mined.

### Steps to reproduce

1. Place a core block
2. Mine it
3. Nothing drops

### Expected behaviour

When mined, the core blocks should drop themselves.

### Information

- [X] I have provided as much information as possible

**Comment by manmaed** [comment]
Fixed in Build 0.7.5
